# Generated by Django 6.0.3 on 2026-04-02 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('submissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_disease_name', models.CharField(max_length=255)),
                ('final_recommendation', models.TextField()),
                ('expert_notes', models.TextField(blank=True, null=True)),
                ('review_status', models.CharField(choices=[('approved', 'Approved'), ('corrected', 'Corrected'), ('rejected', 'Rejected')], max_length=20)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='submissions.submission')),
            ],
        ),
    ]
